### PR TITLE
pull

### PR DESCRIPTION
**Pull request by phancddev**

### CODE REVIEW

**Comment by engageub** [comment]
Hi,
It looks like you may have sent a wrong request.
Thank you

**Comment by phancddev** [comment]
sorry
but can I have your email address? I want to talk something

Vào Th 5, 4 thg 1, 2024 vào lúc 22:09 engageub ***@***.***>
đã viết:

**Comment by engageub** [comment]
Hello,
If its related to InternetIncome script, please start a discussion in the following link.
https://github.com/engageub/InternetIncome/discussions
I do not make custom scripts, so please do not expect anything apart from InternetIncome script. 

Thank you

**Comment by phancddev** [comment]
I mean Can u optimize source code?

**Comment by engageub** [comment]
The script is one time start and does not interfere after the containers are started. 
If you are an advanced user, please have a look at test branch.
It provides multi ip and multi vpn support. 

https://github.com/engageub/InternetIncome/tree/test

Thank you

**Comment by phancddev** [comment]
Yes, I knew. Thanks for ur support! But I meant if we can optimize the
container proxy, we can use more proxy!

**Comment by phancddev** [comment]
Oh yeh thanks!
Maybe use many containers to connect proxy is heavy

**Comment by engageub** [comment]
Please check the cpu and memory utilization of each proxy container.
Disable logs for optimization. 

Thank you

**Comment by phancddev** [comment]
For example:
I have vps 4-8 and I run traffmonetizer
If container proxy optimized I can run 500 proxy for traffmonetizer! But
the proxy containers is so heavy so only run 200 proxy

Thanks!

**Comment by engageub** [comment]
For traffmonetizer, you can use proxychains without docker.
It was confirmed to be working by some users. 

Thank you

**Comment by phancddev** [comment]
I dont know how to make it automatic 😭😭😭😭

**Comment by engageub** [comment]
You can follow this to use proxychains.

https://github.com/haad/proxychains

Thank you

**Comment by phancddev** [comment]
Do you have source code for use multi proxy.

Very thanks!

**Comment by engageub** [comment]
No. I currently do not have but you can use "for" loop in linux iterating over the proxy files.
You may raise an issue there if its not working as expected. 

Thank you

**Comment by phancddev** [comment]
Yes. But I dont have experience to do it. Hope to your new source in future
😭

**Comment by engageub** [comment]
From your repositories, I see that you have made multiple changes related to proxies written in python.
An example below. So I believe it should not be difficult for you. 

https://github.com/phancddev/traffic_link_proxy


Thank you

**Comment by phancddev** [comment]
I write with chatgpt support haha. But i really dont know how to config to
multi proxy for traff

**Comment by engageub** [comment]
You will have to confirm it working with one proxy, then you can write "for" loop.


Thank you

**Comment by phancddev** [comment]
Ok, I will do that.

Thanks for ur support!

**Comment by engageub** [comment]
You may ask proxychains support if one proxy is not working.


Thank you

**Comment by phancddev** [comment]
Okay, thank you!

**Comment by phancddev** [comment]
If have any optimize with proxy containers. I hope it
Many thanks!

**Comment by engageub** [comment]
Hello,
If you have more than 1000 proxies, you may use [test branch](https://github.com/engageub/InternetIncome/tree/test) by setting `USE_CUSTOM_NETWORK=true` in `properties.conf`.

Thank you

**Comment by phancddev** [comment]
oh thank you!!

Vào Th 4, 25 thg 12, 2024 vào lúc 04:20 engageub ***@***.***>
đã viết:

**Comment by phancddev** [comment]
can I have your contact?

Vào Th 4, 25 thg 12, 2024 vào lúc 04:20 engageub ***@***.***>
đã viết:

**Comment by engageub** [comment]
Hello,
You can contact me for anything related to InternetIncome script via Issues or Discussions  in github.

Thank you

**Pull request closed without merging**
