### PR TITLE
Update internetIncome.sh to add spide.network

### PR DESCRIPTION
**Pull request by sebastian-salmhofer**
Added spide.network service.
You first have to start the node and it generates two keys, a machine key and a device key. You have to paste the device key on the website to register the node. The machine key has to be used to start the container again with the same machine and device key. I am saving them into two separate files that are backed up. spide_machine.txt is necessary to restart the node(s) and spide_device.txt is handy to have all IDs in one file to register them on their website.

I don't know yet how profitable spide is, I just added it to test it.

### CODE REVIEW

**Comment by engageub** [comment]
Hello,

Thank you for submitting the pull request.
 I would like to bring to your attention that I am already aware of this. In fact, I suggested about the changes to be made in the container. 

https://github.com/XternA/spide-network/issues/1 

It is essential to enable logging by default, as the current implementation does not retrieve the ID when logs are disabled. I intend to incorporate these changes into the test and not main branch, since users had issues with this app, and there has been a lack of responses to their queries as well as delayed/no payments.


For reference, here is the link to the relevant Reddit discussion: https://www.reddit.com/r/spidenetwork/


Additionally, have you made a withdrawal and received your payout?


Thank you

**Comment by engageub** [comment]
Hello,
I appreciate the effort you put into writing the code.
I had a look into the code and have few concerns.
Although, I am not proceeding with this pull request now, I would like to highlight few concerns.

1. I see that you tried to start the docker container 3 times.  You can write all the logic before starting the container and pass the parameters. Only the valid parameters will work and the remaining parameters would be blank if not specified.
2. We are not sure when we would be getting the device ID, so it should not be immediate. The [test] branch handles device id generation logic. There is a separate file `generateDeviceIds.sh` to get the device Ids from containers. We wait for 30 seconds after all the containers are started and then generate device Ids. 


Thank you

**Comment by engageub** [comment]
> I noticed that with logging, so I removed the variable that can disable logging from the docker run commands that are used to create the IDs. Maybe it would be even better to explicitly enable it. I don't know if you could disable it systemwide, I don't have that much experience with docker.
> 
> But if you know about problems with them maybe better wait. I just registered there today and I am testing it with 10 nodes at the moment. So far I didn't earn anything, but it's only been up for a couple of hours. So I couldn't try to payout yet.

Yes, I did see that the log variable has been removed from the code as it would not work if logging is disabled globally. That's the way it should be if the container relies on logs but the global variable in `properties.conf` to disable logs will not make any difference. 

The problems have been mentioned by users in their official Reddit Channel and there was no response from them yet.
So, will wait until someone confirms the payout. 

Thank you

**Comment by sebastian-salmhofer** [comment]
> Hello, I appreciate the effort you put into writing the code. I had a look into the code and have few concerns. Although, I am not proceeding with this pull request now, I would like to highlight few issues.
> 
> 1. I see that you tried to start the docker container 3 times.  You can write all the logic before starting the container and pass the parameters. Only the valid parameters will work and the remaining parameters would be blank if not specified.
> 2. We are not sure when we would be getting the device ID, so it should not be immediate. The [test](https://github.com/engageub/InternetIncome/blob/main/internetIncome.sh) branch handles device id generation logic. There is a separate file `generateDeviceIds.sh` to get the device Ids from containers. We wait for 30 seconds after all the containers are started and then generate device Ids.
> 
> Thank you

Yes, good points. I just made this quickly to test it and it worked fine for me. I'll wait if the service actually works and is worth it. If it is I will improve it.

**Pull request closed without merging**
